{{- if .Values.rayHead.ingress.enabled -}}
{{- $fullName := include "anant-enterprise.fullname" . -}}
{{- $svcPort := .Values.rayHead.service.port -}}
{{- if and .Values.rayHead.ingress.className (not (hasKey .Values.rayHead.ingress.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set .Values.rayHead.ingress.annotations "kubernetes.io/ingress.class" .Values.rayHead.ingress.className}}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "anant-enterprise.labels" . | nindent 4 }}
  {{- with .Values.rayHead.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.rayHead.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.rayHead.ingress.className }}
  {{- end }}
  {{- if .Values.rayHead.ingress.tls }}
  tls:
    {{- range .Values.rayHead.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.rayHead.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "anant-enterprise.rayHeadServiceName" $ }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ include "anant-enterprise.rayHeadServiceName" $ }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
---
{{- if .Values.rayHead.ingress.enabled }}
{{- $dashboardSvcName := printf "%s-dashboard" $fullName -}}
{{- $dashboardPort := .Values.rayHead.service.dashboardPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-dashboard
  labels:
    {{- include "anant-enterprise.labels" . | nindent 4 }}
    service.type: dashboard
  annotations:
    {{- with .Values.rayHead.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  {{- if and .Values.rayHead.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.rayHead.ingress.className }}
  {{- end }}
  {{- if .Values.rayHead.ingress.tls }}
  tls:
    {{- range .Values.rayHead.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.rayHead.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /dashboard(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $dashboardSvcName }}
                port:
                  number: 80
    {{- end }}
{{- end }}
{{- end }}