{{- if .Values.rayHead.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anant-enterprise.fullname" . }}-ray-head
  labels:
    {{- include "anant-enterprise.rayHeadLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rayHead.replicaCount }}
  selector:
    matchLabels:
      {{- include "anant-enterprise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ray-head
  template:
    metadata:
      labels:
        {{- include "anant-enterprise.rayHeadLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "anant-enterprise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ray-head
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              ray start --head \
                --dashboard-host=0.0.0.0 \
                --dashboard-port={{ .Values.anant.ray.dashboardPort }} \
                --port=10001 \
                --redis-password=${RAY_REDIS_PASSWORD} &&
              python ray_anant_cluster.py --mode=head
          ports:
            - name: api
              containerPort: 8000
              protocol: TCP
            - name: dashboard
              containerPort: {{ .Values.anant.ray.dashboardPort }}
              protocol: TCP
            - name: ray-client
              containerPort: 10001
              protocol: TCP
          env:
            {{- include "anant-enterprise.commonEnvVars" . | nindent 12 }}
            {{- include "anant-enterprise.securityEnvVars" . | nindent 12 }}
            - name: RAY_HEAD_NODE
              value: "true"
            - name: RAY_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "anant-enterprise.fullname" . }}-secrets
                  key: ray-redis-password
          livenessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: api
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.rayHead.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: logs
              mountPath: /app/logs
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: data
          {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "anant-enterprise.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: logs
          {{- if .Values.persistence.logs.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "anant-enterprise.fullname" . }}-logs
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp
          emptyDir: {}
      {{- with .Values.rayHead.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rayHead.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rayHead.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}